name: Dart

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        sdk: [stable]
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1.4
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: |
          dart format --output=none --set-exit-if-changed $(find lib/src -name "*.dart" -not \( -name "*models.dart" \) )
          dart format --output=none --set-exit-if-changed $(find test -name "*.dart" )

      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: dart test -x full_perft
